const char *licences = 
"\nLibraries inside pumpcontrol:\n"  
"JSON for Modern C++\n"
"https://github.com/nlohmann/json\n"
"The MIT License (MIT)\n"
"Copyright (c) 2013-2016 Niels Lohmann <http://nlohmann.me>.\n"
"---------------------------------------------------------------------------\n"
"Easylogging++\n"
"https://github.com/muflihun/easyloggingpp\n"
"The MIT License (MIT)\n"
"Copyright (c) 2017 Muflihun Labs\n"
"---------------------------------------------------------------------------\n"
"firmatacpp\n"
"https://github.com/simlrh/firmatacpp\n"
"Copyright 2016 Steve Le Roy Harris\n"
"---------------------------------------------------------------------------\n"
"serial\n"
"https://github.com/wjwwood/serial\n"
"The MIT License\n"
"Copyright (c) 2012 William Woodall, John Harrison\n"
"---------------------------------------------------------------------------\n"
"websocketpp\n"
"https://github.com/zaphoyd/websocketpp\n"
"Copyright (c) 2014, Peter Thorson. All rights reserved.\n\n";